### PR TITLE
fix: add dark mode toggle to mobile layout

### LINKED ISSUE #83: Mobile Layout is Missing Dark Mode Toggle
**Describe the bug** 
Unable to toggle between light/dark mode on mobile devices

**To Reproduce**

1. Visit the page on a small mobile device
2. Frantically search for those sunglasses you never bought

**Expected behavior**

1. Visit the page on small mobile device
2. Have minor discomfort before being able to enable dark mode
3. Rejoice, knowing you've saved money not having to buy those sunglasses

**Screenshots**

image

### PR DESCRIPTION
**Pull request by devonzara**
Closes #83

Before/After
image

### CODE REVIEW

**Comment by kennethcassel** [comment]
Icon isn't showing up on iOS mobile safari 

 image

image

**Comment by devonzara** [comment]
Good catch. Not sure why they don't work... they appeared fine in Chrome's dev tools mobile mode. Adding an explicit width seems to fix it though. 👍🏼

**Comment by kennethcassel** [comment]
Looks like that fixed it! :) we got some merge conflicts. I merged some PR's this morning, so might need to merge in the most recent main and push up that commit

**Comment by kennethcassel** [comment]
@all-contributors add @devonzara as a code contributor :)

**Pull request merged**
