### PR TITLE
fix: screen flash on changing themes

### LINKED ISSUE #75: Screen flashes when changing pages in dark mode
**Describe the bug** 
In dark mode, the screen flashes when navigating to a new page

**To Reproduce** Steps to reproduce the behavior:

Visit runwasm.com in dark mode. 
Click on one of the internal links in header. 
See white flash.

**Expected behavior** 
No flashing when navigating pages.

**Screenshots** 

https://user-images.githubusercontent.com/22961671/135466053-fe06de2b-7cac-4c92-a958-2eb665a5f617.mov

### PR DESCRIPTION
**Pull request by Deep-Codes**
Attempts to fix #75 

There are 2 approaches for this issue

1. Run a script in the `<head>` tag

This works well when was have theme data attribute in the HTML element So when the page loads we can get the theme based on preference and localStorage and assign it before the `<body>` starts executing.

```js
const docHtml = document.documentElement.dataset;
docHtml.theme =getTheme();
```

and then we add it  to `_document.tsx`

```tsx
import Document, { Html, Head, Main, NextScript } from 'next/document';
import React from 'react';

class MyDocument extends Document {
    render() {
        return (
            <Html lang="en">
                <Head>
                    {/* To Avoid Flickering */}
                    <script type="text/javascript" src="/static/theme.js" />
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
    }
}

export default MyDocument;
```

--- 

Since we aren't using the data theme attribute here instead we are assigning the theme based on className to the `body` element.

2. Using [`next-themes`](https://github.com/pacocoursey/next-themes)

Things I have done in this PR:

- added the package `next-themes` (1.59 kb)
- wrapped app component with `<ThemeProvider />`
- by default `next-themes` uses data attribute so passing `attribute="class"`
- adding base styles to body `<body className="bg-white dark:bg-gray-875">`
- using `useTheme()` hook to get current theme and setTheme function to toggle

Some implementations 

https://github.com/leerob/leerob.io/blob/7bd1fdfdb0f5bf7ad0945b14f7a0da26eaa68c11/pages/_app.tsx#L13

### CODE REVIEW

**Comment by kennethcassel** [comment]
Thanks for the PR and detailed info! Can you resolve the merge conflicts? We merged a few PR earlier today (dark mode toggle seems to be missing on your preview deploy)

**Comment by Deep-Codes** [comment]
> Thanks for the PR and detailed info! Can you resolve the merge conflicts? We merged a few PR earlier today (dark mode toggle seems to be missing on your preview deploy)

Yeah was on it, doing

**Comment by kennethcassel** [comment]
Ah one small thing is the toggle icon isn't showing up on mobile safari

 image

**Comment by Deep-Codes** [comment]
> Ah one small thing is the toggle icon isn't showing up on mobile safari
> 
> image

Simulator Screen Shot - iPhone 12 Pro Max - 2021-10-02 at 06 24 32

Adding width and height should solve it commiting

**Comment by Deep-Codes** [comment]
Verified on iPhone Safari let me know if anything else 👍🏽

**Comment by kennethcassel** [comment]
It's great thank you!

**Pull request merged**
